"""Dictionary of urls, this data is used in the Extraction pipeline unit tests."""

# flake8: noqa
url_dict = {
    "business_standard_1": "https://www.business-standard.com/article/international/walmart-disney-suspend-contributions-to-us-lawmakers-who-opposed-biden-win-121011300172_1.html",
    "business_standard_2": "https://www.business-standard.com/article/international/us-house-committee-releases-report-supporting-donald-trump-s-impeachment-121011300125_1.html",
    "business_standard_3": "https://www.business-standard.com/article/international/wb-economist-china-will-need-to-learn-to-restructure-emerging-market-debt-121011300034_1.html",
    "business_standard_4": "https://www.business-standard.com/article/current-affairs/death-of-galaxy-galactic-collision-spews-gases-equal-to-10-000-suns-a-year-121011300543_1.html",
    "business_standard_5": "https://www.business-standard.com/article/markets/auto-psu-stocks-to-outperform-in-the-short-term-vinay-rajani-of-hdfc-sec-121011300139_1.html",

    "economic_times_1": "https://economictimes.indiatimes.com/news/economy/policy/government-mops-up-rs-8660-cr-from-disinvestment-in-02/articleshow/33105933.cms",
    "economic_times_2": "https://economictimes.indiatimes.com/news/politics-and-nation/delhi-policeman-nabbed-for-taking-bribe-from-kidney-racketeer/articleshow/2785146.cms",
    "economic_times_3": "https://economictimes.indiatimes.com/industry/services/education/indian-universities-look-abroad-for-success-at-home/articleshow/5957175.cms",
    "economic_times_4": "https://economictimes.indiatimes.com/industry/transportation/railways/conviction-rate-in-theft-cases-in-central-railways-mumbai-division-falls-steeply/articleshow/48554953.cms",
    "economic_times_5": "https://economictimes.indiatimes.com/news/politics-and-nation/centre-always-ready-for-talks-dialogue-would-fetch-solution-manohar-lal-khattar-to-farmers/articleshow/79444811.cms",
    "economic_times_6": "https://economictimes.indiatimes.com/news/politics-and-nation/modi-toiling-with-rs-10000-per-annum-payment-to-farmers/articleshow/67385159.cms",

    "times_of_india_1": "https://timesofindia.indiatimes.com/city/bengaluru/ISROs-second-launch-pad-to-be-sent-by-March-end/articleshow/3801270.cms",
    "times_of_india_2": "https://timesofindia.indiatimes.com/city/delhi/CBSE-makes-more-room-for-kids-with-special-needs/articleshow/4202742.cms",
    "times_of_india_3": "https://timesofindia.indiatimes.com/entertainment/events/lucknow/Freshers-join-in-to-participate-in-Clean-Clear-Lucknow-Times-Fresh-Face-2012-at-Shri-Ramswaroop-Memorial-College/articleshow/16463875.cms?",
    "times_of_india_4": "https://timesofindia.indiatimes.com/home/education/news/iit-madras-disappointed-over-not-granted-institutes-of-eminence-status-writes-to-hrd-ministry/articleshow/66356947.cms?",
    "times_of_india_5": "https://timesofindia.indiatimes.com/city/jaipur/nine-samples-of-uk-returned-and-their-contacts-test-negative-for-uks-mutated-covid-19-strain-report-of-two-awaited/articleshow/80034547.cms",
    "times_of_india_6": "https://timesofindia.indiatimes.com/life-style/relationships/love-sex/how-to-make-time-for-intimacy-in-your-love-life-according-to-zodiac-signs/photostory/80667320.cms",
    "times_of_india_7": "https://timesofindia.indiatimes.com/blogs/toi-edit-page/turn-the-tide-against-cancer-india-needs-affordable-and-accessible-cancer-treatment-else-cancer-screenings-arent-much-use/",

    "deccan_herald_1": "https://www.deccanherald.com/content/1368/agriculture-department-urged-regulate-fertilisers.html",
    "deccan_herald_2": "https://www.deccanherald.com/content/273743/pak-needs-explain-osamas-presence.html",
    "deccan_herald_3": "https://www.deccanherald.com/content/507817/children-adopted-through-state-governmentsmother.html",
    "deccan_herald_4": "https://www.deccanherald.com/5-dk-take-part-special-705298.html",
    "deccan_herald_5": "https://www.deccanherald.com/national/east-and-northeast/switching-from-poppy-to-cardamom-arunachal-district-farmers-set-to-taste-success-in-2021-933703.html",

    "ndtv_1": "https://sports.ndtv.com/cricket/we-cant-influence-indian-high-commission-for-visas-pcb-1594242",
    "ndtv_2": "https://www.ndtv.com/india-news/bjp-and-congress-lock-horns-over-newspaper-advertisements-in-poll-bound-himachal-pradesh-503275",
    "ndtv_3": "https://www.ndtv.com/polls/delhis-true-menace-come-from-its-air-water-food-and-flies-do-you-agree-767644",
    "ndtv_4": "https://www.ndtv.com/india-news/spread-of-japanese-encephalitis-in-poorvanchal-due-to-lack-of-sanitation-up-chief-minister-yogi-adit-1687935",
    "ndtv_5": "https://www.ndtv.com/entertainment/sean-connery-a-legend-on-screen-and-off-tributes-from-hugh-jackman-abhishek-bachchan-and-others-2318676",
    "ndtv_6": "https://gadgets.ndtv.com/entertainment/news/little-things-season-2-release-date-trailer-netflix-1911696",
    "ndtv_7": "https://www.ndtv.com/education/jee-main-2021-know-preparation-tips-salient-topics-and-weightage",
    "ndtv_8": "https://swachhindia.ndtv.com/air-pollution-crisis-delhi-air-quality-in-severe-category-for-third-consecutive-day-29289/",
    "ndtv_9": "https://www.carandbike.com/news/maruti-suzuki-has-sold-4-million-pre-owned-vehicles-in-india-in-19-years-2362794",

    "independent_1": "https://www.independent.co.uk/news/world/americas/elijah-mcclain-death-colorado-police-black-lives-matter-george-floyd-police-a9584366.html",
    "independent_2": "https://www.independent.co.uk/news/uk/home-news/coronavirus-childcare-parents-lockdown-schools-a9688116.html",
    "independent_3": "https://www.independent.co.uk/arts-entertainment/tv/news/ratched-netflix-trigger-warning-child-abuse-suicide-violence-sarah-paulson-b571405.html",
    "independent_4": "https://www.independent.co.uk/life-style/royal-family/the-crown-queen-cousins-nerissa-katherine-bowes-lyon-b1721187.html",
    "independent_5": "https://www.independent.co.uk/arts-entertainment/tv/news/bridgerton-violet-actor-ruth-gemmell-tracy-beaker-b1780757.html",

    "evening_standard_1": "https://www.standard.co.uk/news/uk/boris-johnson-u-turn-free-school-meals-marcus-rashford-a4470506.html",
    "evening_standard_2": "https://www.standard.co.uk/news/politics/david-cameron-warns-uk-will-lose-respect-overseas-with-foreign-aid-department-merger-a4470651.html",
    "evening_standard_3": "https://www.standard.co.uk/news/uk/christmas-bubbles-science-sage-advice-b79264.html",
    "evening_standard_4": "https://www.standard.co.uk/news/uk/jeremy-corbyn-joke-hignfy-bbc-b79298.html",
    "evening_standard_5": "https://www.standard.co.uk/reveller/restaurants/tier-2-single-household-any-table-size-restaurants-b79359.html",

    "new_york_post_1": "https://nypost.com/2010/09/27/brooklyn-tea-party-rallies-against-ground-zero-mosque-multiculturalism/",
    "new_york_post_2": "https://nypost.com/2015/05/21/syndergaards-goal-for-what-may-be-his-last-mlb-start-for-a-while/",
    "new_york_post_3": "https://nypost.com/2017/06/08/scaramucci-may-have-finally-landed-a-gig-in-the-trump-administration/",
    "new_york_post_4": "https://nypost.com/2019/10/30/campaign-for-disgraced-ex-cop-daniel-pantaleo-raises-more-than-170k/",
    "new_york_post_5": "https://nypost.com/2020/12/31/country-singer-reunited-with-cat-after-nashville-bombing/",

    "express_1": "https://www.express.co.uk/news/politics/1369685/brexit-news-uk-eu-trade-deal-france-fishing-emmanuel-macron-no-deal-latest",
    "express_2": "https://www.express.co.uk/news/weather/1370081/BBC-Weather-Europe-snow-forecast-cold-December-update-video-vn",
    "express_3": "https://www.express.co.uk/news/politics/1383306/Brexit-live-latest-brexit-deal-Northern-Ireland-customs-boris-johnson-john-redwood",
    "express_4": "https://www.express.co.uk/news/world/1369648/India-news-mystery-illness-coronavirus-covid-Andhra-Pradesh-eluru-disease-cause-ont",
    "express_5": "https://www.express.co.uk/news/science/1369261/bible-apocalypse-burnt-great-pyramid-isaac-newton-occult-pyramidology-study-sothebys-evg",

    "usa_today_1": "https://www.usatoday.com/story/news/politics/2020/12/07/trump-white-house-covid-summit-fda-vaccine-approval/3861768001/",
    "usa_today_2": "https://www.usatoday.com/videos/news/2020/12/08/dan-gable-wrestling-legend-awarded-presidential-medal-freedom/6485478002/",
    "usa_today_3": "https://www.usatoday.com/story/news/nation/2020/12/07/north-atlantic-right-whale-endangered-species-newborns/6484190002/",
    "usa_today_4": "https://www.usatoday.com/story/sports/mls/2020/12/07/mls-cup-2020-seattle-sounders-advance-play-columbus-crew-title/6487291002/",
    "usa_today_5": "https://www.usatoday.com/story/entertainment/books/2020/12/08/bob-woodward-robert-costa-pen-book-trumps-final-days-president/6487779002/",

    "daily_mail_1": "https://www.dailymail.co.uk/news/article-8988283/EU-British-boys-BANNED-playing-young-Prince-William.html",
    "daily_mail_2": "https://www.dailymail.co.uk/tvshowbiz/article-8988259/TOM-LEONARD-Stars-haunt-mischief-menu.html",
    "daily_mail_3": "https://www.dailymail.co.uk/sciencetech/article-8988053/NASA-astronaut-Victor-Glover-shares-video-SPACE.html",
    "daily_mail_4": "https://www.dailymail.co.uk/sport/football/article-8987295/Pierre-Emile-Hojbjerg-Jose-Mourinhos-midfield-general-high-flying-Spurs.html",
    "daily_mail_5": "https://www.dailymail.co.uk/sport/football/article-8986989/The-key-battles-Tottenhams-table-clash-Chelsea-Stamford-Bridge.html",
    "daily_mail_6": "https://www.dailymail.co.uk/tvshowbiz/article-2937220/Lucy-Mecklenburgh-Thom-Evans-Robbie-Savage-help-PG-Tips-Monkey-prepare-Red-Nose-Day-Challenge.html",
    "daily_mail_7": "https://www.dailymail.co.uk/news/article-2937206/Halal-abattoir-staff-hacked-taunted-sheep-One-worker-sacked-three-suspended-caught-camera-carrying-horrifying-routine-abuse.html",

    "india_today_1": "https://www.indiatoday.in/india/story/pm-modi-launch-covid-vaccination-drive-jan-16-cowin-app-coronavirus-covaxin-covishield-1758628-2021-01-13",
    "india_today_2": "https://www.indiatoday.in/technology/news/story/amazon-great-republic-day-sale-announced-from-january-20-deals-bank-offers-and-more-1758622-2021-01-13",
    "india_today_3": "https://www.indiatoday.in/sports/cricket/story/a-win-at-gabba-will-give-india-their-greatest-test-series-victory-ever-says-akhtar-1758619-2021-01-13",
    "india_today_4": "https://www.indiatoday.in/sports/cricket/story/australia-vs-india-tim-paine-apology-not-forced-remorseful-stump-mic-rashwin-sydney-1758534-2021-01-13",
    "india_today_5": "https://www.indiatoday.in/coronavirus-outbreak/story/covid-vaccines-shipped-safety-concern-indians-1758506-2021-01-13",

    "one_india_1": "https://www.oneindia.com/india/congress-leader-dk-shivakumar-to-appear-before-cbi-in-disproportionate-assets-case-today-3180984.html",
    "one_india_2": "https://www.oneindia.com/india/will-make-bengal-police-lick-boots-if-bjp-comes-to-power-in-next-assembly-elections-raju-banerjee-3181010.html",
    "one_india_3": "https://www.oneindia.com/india/cyclone-nivar-to-hit-tn-with-winds-at-145-kmph-puducherry-lg-kiran-bedi-appeals-people-to-stay-safe-3181023.html",
    "one_india_4": "https://www.oneindia.com/india/delhi-riots-umar-khalid-didn-t-take-security-to-conspiratorial-meetings-says-charge-sheet-3181302.html",
    "one_india_5": "https://www.oneindia.com/international/xi-jinping-finally-congratulates-biden-hopes-us-china-will-uphold-spirit-of-non-confrontation-3181336.html",

    "hindu_business_line_1": "https://www.thehindubusinessline.com/todays-paper/tp-news/article33274819.ece",
    "hindu_business_line_2": "https://www.thehindubusinessline.com/money-and-banking/delegation-of-ambassadors-high-commissionersvisits-bharat-biotech-to-discuss-progress-of-covaxin/article33289689.ece",
    "hindu_business_line_3": "https://www.thehindubusinessline.com/todays-paper/article33294244.ece",
    "hindu_business_line_4": "https://www.thehindubusinessline.com/money-and-banking/pull-payments-made-on-behalf-of-merchants-acquirer-banks-should-not-push-consumers-to-pay-for-services/article33299994.ece",
    "hindu_business_line_5": "https://www.thehindubusinessline.com/money-and-banking/rbi-to-kotak-mahindra-bank-no-dividend-payment-on-perpetual-non-cumulative-preference-shares/article33299037.ece",

    "scroll_news_1": "https://scroll.in/field/979390/they-can-beat-australia-in-their-own-den-shastri-backs-india-s-fabulous-five-quicks-to-shine",
    "scroll_news_2": "https://scroll.in/field/979393/champions-league-last-gasp-wins-take-juventus-chelsea-and-sevilla-into-last-16-barcelona-cruise",
    "scroll_news_3": "https://scroll.in/latest/979391/coronavirus-india-reports-44376-new-cases-tally-crosses-92-lakh",
    "scroll_news_4": "https://scroll.in/article/979318/what-is-the-extent-of-caste-segregation-in-indian-villages-today-new-data-gives-us-an-idea",
    "scroll_news_5": "https://scroll.in/latest/979410/khichdification-ima-demands-withdrawal-of-move-allowing-ayurveda-doctors-to-perform-surgery",
    "scroll_news_6": "https://scroll.in/reel/985764/why-beginning-on-mubi-is-a-film-you-cannot-miss",
    "scroll_news_7": "https://scroll.in/article/985739/ground-report-in-haryana-farmer-protests-run-into-a-caste-divide",

    "cnbc_1": "https://www.cnbc.com/2020/12/25/the-plant-based-meat-industry-is-on-the-rise-but-challenges-remain.html",
    "cnbc_2": "https://www.cnbc.com/2020/12/25/covid-stimulus-why-lawmakers-hope-trump-signs-the-bill-very-quietly.html",
    "cnbc_3": "https://www.cnbc.com/2020/12/25/biden-and-trump-christmas-messages.html",
    "cnbc_4": "https://www.cnbc.com/2020/12/24/dominion-voting-warns-fox-news-lawsuits-are-imminent.html",
    "cnbc_5": "https://www.cnbc.com/2020/12/24/wonder-woman-1984-box-office-preview-what-the-superhero-film-can-make.html",
    "cnbc_6": "https://www.cnbc.com/2020/11/01/election-2020-live-updates-biden-in-pennsylvania-as-trump-barnstorms-the-country.html",

    "the_indian_express_1": "https://indianexpress.com/article/world/print/four-killed-as-armed-militants-storm-5-star-hotel-in-pakistans-gwadar-port-city-police-5723193/",
    "the_indian_express_2": "https://indianexpress.com/article/news-archive/ayushman-bharat-aadhaar-mandatory-for-those-seeking-treatment-for-second-time-5390924/",
    "the_indian_express_3": "https://indianexpress.com/article/india/web/bjp-mp-karandlaje-challenges-karnataka-cm-siddaramaiah-govt-to-arrest-her-4996043/",
    "the_indian_express_4": "https://indianexpress.com/article/news-archive/days-are-not-far-when-kashmiri-pandits-would-return-to-their-homes-with-dignity-jk-bjp-4842449/",
    "the_indian_express_5": "https://indianexpress.com/article/news-archive/head-constable-suspended-and-challaned-for-talking-on-cell-phone-while-driving-in-chandigarh-4836554/",
    "the_indian_express_6": "http://archive.indianexpress.com/news/vikram-to-play-villain-in-heropanti/1214798/",
    "the_indian_express_7": "http://archive.indianexpress.com/news/the-role-i-d-die-for-with-arif-zakaria/1214797/",
    "the_indian_express_8": "http://archive.indianexpress.com/news/indias-average-economic-growth-during-upa-i/1214985/0",

    "the_pioneer_1": "https://www.dailypioneer.com/2020/state-editions/punjab-cm-launches----diginest----mobile-app-to-ensure-digital-access-to-state-govt-directory.html",
    "the_pioneer_2": "https://www.dailypioneer.com/2020/state-editions/hc-seeks-reply-from-state-in-2-weeks-on-adi-shankaracharya---s-samadhi.html",
    "the_pioneer_3": "https://www.dailypioneer.com/2020/state-editions/aap-mla-visits-singhu-border-to-ensure-wifi-facilities-for-farmers.html",
    "the_pioneer_4": "https://www.dailypioneer.com/2020/india/govt-ok---s-bank-loans-at-lower-rates-to-distilleries-for-raising-ethanol-production.html",
    "the_pioneer_5": "https://www.dailypioneer.com/2020/state-editions/pil-questions-acquisition-of-university---s-fertile-land-for-constructing-pantnagar-airport.html",

    "financial_express_1": "https://www.financialexpress.com/archive/delhi-power-crisis-gets-worse-arvind-kejriwal-warns-discom-licences-could-be-cancelled/1222283/",
    "financial_express_2": "https://www.financialexpress.com/archive/northeast-student-nido-tania-beaten-to-death-in-delhi-shocked-community-demands-action/1222157/",
    "financial_express_3": "https://www.financialexpress.com/archive/diesel-price-hiked-by-50p-non-subsidised-lpg-cylinder-rate-cut-by-rs-107-day-after-quota-hiked-from-9-to-12/1222195/",
    "financial_express_4": "https://www.financialexpress.com/archive/govt-kills-two-reforms-raises-lpg-cap-snaps-its-aadhaar-link-rahul-gandhis-wish-will-cost-rs-5000-cr/1222008/",
    "financial_express_5": "https://www.financialexpress.com/archive/rbi-governor-raghuram-rajan-effects-dramatic-shift-as-india-quietly-begins-tryst-with-inflation-targeting/1221591/",

    "euro_news_1": "https://www.euronews.com/2020/12/08/france-s-next-aircraft-carrier-to-be-nuclear-powered-macron-confirms",
    "euro_news_2": "https://www.euronews.com/2020/12/08/charlie-hebdo-trial-prosecutors-request-30-year-sentence-for-fugitive-widow-of-attacker",
    "euro_news_3": "https://www.euronews.com/2020/12/08/election-misinformation-isn-t-an-american-phenomenon-it-s-spreading-across-europe-too-view",
    "euro_news_4": "https://www.euronews.com/2020/12/09/the-eu-must-leverage-closer-trade-ties-with-uzbekistan-to-ensure-progress-on-human-rights-",
    "euro_news_5": "https://www.euronews.com/2020/12/09/budapest-and-warsaw-protest-their-governments-budget-veto-by-lighting-monuments-eu-blue",

    "espn_cricinfo_1": "https://www.espncricinfo.com/series/vitality-blast-2020-1207645/nottinghamshire-vs-leicestershire-1st-quarter-final-1207789/match-report",
    "espn_cricinfo_2": "https://www.espncricinfo.com/story/vitality-t20-blast-mitchell-claydon-misses-sussex-s-t20-blast-defeat-after-hand-sanitiser-ball-tampering-ban-1234150",
    "espn_cricinfo_3": "https://www.espncricinfo.com/story/azeem-rafiq-calls-for-witness-anonymity-in-yorkshire-racism-investigation-1234146",
    "espn_cricinfo_4": "https://www.espncricinfo.com/story/ipl-2020-jofra-archer-thriving-in-different-type-of-pressure-at-ipl-says-rajasthan-royals-team-mate-jos-buttler-1234126",
    "espn_cricinfo_5": "https://www.espncricinfo.com/story/icc-women-s-rankings-england-s-sarah-glenn-reaches-career-best-t20i-rankings-meg-lanning-moves-up-1234107",

    "new_york_times_1": "https://www.nytimes.com/2020/01/27/us/politics/impeachment-live.html",
    "new_york_times_2": "https://www.nytimes.com/2020/01/14/books/review-serious-noticing-james-wood.html",
    "new_york_times_3": "https://www.nytimes.com/2020/01/31/learning/is-it-offensive-for-sports-teams-and-their-fans-to-use-native-american-names-imagery-and-gestures.html",
    "new_york_times_4": "https://www.nytimes.com/2020/01/09/world/middleeast/iran-plane-crash-ukraine.html",
    "new_york_times_5": "https://www.nytimes.com/2020/01/07/us/politics/joe-biden-elizabeth-warren-foreign-policy.html",

    "date_extractor_dummy_1": "https://www.date_extractor_dummy_1.com/",
    "date_extractor_dummy_2": "https://www.date_extractor_dummy_2.com/",
    "date_extractor_dummy_3": "https://www.date_extractor_dummy_3.com/",
    "date_extractor_dummy_4": "https://www.date_extractor_dummy_4.com/",
    "date_extractor_dummy_5": "https://www.date_extractor_dummy_5.com/",
    "date_extractor_dummy_6": "https://www.date_extractor_dummy_6.com/",
    "date_extractor_dummy_7": "https://www.date_extractor_dummy_7.com/",
    "date_extractor_dummy_8": "https://www.date_extractor_dummy_8.com/",
    "date_extractor_dummy_9": "https://www.date_extractor_dummy_9.com/",
    "date_extractor_dummy_10": "https://www.date_extractor_dummy_10.com/",
    "date_extractor_dummy_11": "https://www.date_extractor_dummy_11.com/",
    "date_extractor_dummy_12": "https://www.date_extractor_dummy_12.com/",
    "date_extractor_dummy_13": "https://www.date_extractor_dummy_13.com/",
    "date_extractor_dummy_14": "https://www.date_extractor_dummy_14.com/",
    "date_extractor_dummy_15": "https://www.date_extractor_dummy_15.com/",
    "date_extractor_dummy_16": "https://www.date_extractor_dummy_16.com/",
    "date_extractor_dummy_17": "https://www.date_extractor_dummy_17.com/",
    "date_extractor_dummy_18": "https://www.date_extractor_dummy_18.com/",
    "date_extractor_dummy_19": "https://www.date_extractor_dummy_19.com/",
    "date_extractor_dummy_20": "https://www.date_extractor_dummy_20.com/",
    "date_extractor_dummy_21": "https://www.date_extractor_dummy_21.com/",
    "date_extractor_dummy_22": "https://www.date_extractor_dummy_22.com/",
    "date_extractor_dummy_23": "https://www.date_extractor_dummy_23.com/",
    "date_extractor_dummy_24": "https://www.date_extractor_dummy_24.com/",
    "date_extractor_dummy_25": "https://www.date_extractor_dummy_25.com/",
    "date_extractor_dummy_26": "https://www.date_extractor_dummy_26.com/",
    "date_extractor_dummy_27": "https://www.date_extractor_dummy_27.com/",
    "date_extractor_dummy_28": "https://www.date_extractor_dummy_28.com/",
    "date_extractor_dummy_29": "https://www.date_extractor_dummy_29.com/",
    "date_extractor_dummy_30": "https://www.date_extractor_dummy_30.com/",
    "date_extractor_dummy_31": "https://www.date_extractor_dummy_31.com/",
    "date_extractor_dummy_32": "https://www.date_extractor_dummy_32.com/",
    "date_extractor_dummy_33": "https://www.date_extractor_dummy_33.com/",
    "date_extractor_dummy_34": "https://www.date_extractor_dummy_34.com/",
    "date_extractor_dummy_35": "https://www.date_extractor_dummy_35.com/",
    "date_extractor_dummy_36": "https://www.date_extractor_dummy_36.com/",
    "date_extractor_dummy_37": "https://www.date_extractor_dummy_37.com/",
    "date_extractor_dummy_38": "https://www.date_extractor_dummy_38.com/",
    "date_extractor_dummy_39": "https://www.date_extractor_dummy_39.com/",
    "date_extractor_dummy_40": "https://www.date_extractor_dummy_40.com/",
    "date_extractor_dummy_41": "https://www.date_extractor_dummy_41.com/",
    "date_extractor_dummy_42": "https://www.date_extractor_dummy_42.com/",
    "date_extractor_dummy_43": "https://www.date_extractor_dummy_43.com/",

    "blank_1": "https://www.someurl.com/123.html"
}
